server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: register
          uri: ${REGISTER_URL:http://localhost:8081}
          predicates:
            - Path=/api/register/**
        #  filters:
         #   - StripPrefix=1

        - id: barcodes
          uri: ${BARCODES_URL:http://localhost:8081}
          predicates:
            - Path=/api/barcodes/**
         # filters:
         #   - StripPrefix=0

management:
  endpoints:
    web:
      exposure:
        include: health,info